language: node_js
node_js:
  - "9.2.0"
services:
  - redis-server
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - birhanu.hailemariam@gmail.com
cache:
  directories:
    - client/node_modules
    - server/node_modules
#env:
#  - TEST_DIR_CLIENT=client
#  - TEST_DIR_SERVER=server
#script:
  #- cd $TEST_DIR_CLIENT && npm install && npm test
  #- npm run build
jobs:
  include:
    - stage: server
      script: 
        - cd server && npm install && npm run tstart
    - stage: test
      script: 
        - cd server && npm test -- --runInBand
      
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: develop





