language: node_js
node_js:
  - "10.2.1"
services:
  - redis-server
  - docker
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - birhanu.hailemariam@gmail.com
cache:
  directories:
    - client/node_modules
    - server/node_modules
env:
  - TEST_DIR_CLIENT=client
  - TEST_DIR_SERVER=server
#before_script:
#  - cd $TEST_DIR && npm install
#script:
#  - cd $TEST_DIR && npm install && npm test
  #- npm run build
cache:
   directories:
     - node_modules
before_script:
  - cd $TEST_DIR_CLIENT && npm install
  - cd $TEST_DIR_SERVER && npm install
  - cd $TEST_DIR_SERVER && docker-compose build
  - cd $TEST_DIR_SERVER && docker-compose up -d
  - sleep 3
script:
  - cd $TEST_DIR_SERVER && npm test
after_script:
  - cd $TEST_DIR_SERVER && docker-compose kill

#jobs:
#  include:
#    - stage: server
#      script: 
#        - cd server && npm install && npm run tstart
#    - stage: test
#      script: 
#        - cd server && npm test -- --runInBand
      
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: develop





