language: node_js
node_js:
  - 10.2.1
services:
  - redis-server
  - docker
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - birhanu.hailemariam@gmail.com
cache:
  directories:
    - node_modules
  global:
    - secure: eko44dSvSf0XHq2nbNWYOtE2f7UU2eESDDDRoM4ZuxtRebRHnPDoOffuQB9N6+jurRHpd/gCZDq26K9atiNm4znkvisBQ1XEINJlLWfZTetdWt4SJttOVtS1fcTVlUirF6coy8P08EeHrW67WE90phHQWVldu87Gn7OavIfKYZd1dgLrHadSIsRW9YenhCt/w69QiOMeASZcNdTzUammg2lbf6WV45b0QCPPjQqMyoQW02xYp6BgsutijPrLjKiYqgJ0znfHdS+FqJ5gn2HUFmb/B+2iuaULFQ3ZJ4iAws6rfIxQGqZRzFifDxWV2pjD7M2pAjEX/VvJSAj87UX5u9vJh7eOmsERqoxqEoRYRrcTPZhGhk6ROnwjn9Oyxjz615HeuICb1krYguN8vB5pZPjNE/SchGpCJVJmd6Y+1MJbZWa7vYsrzAeerixM0xbt3+DIwGGaybpVXPDRQHZwO5+Yqs3X35ACsU9vB+RyXjLbPgwuNOpEZObX1qpNlDzpc1ezNr3rJT94kJ1zKPZ9llaETYLgYjdi7UP5GKqNKUWN+UVCxOaHWKWhwlkXb8x5qZetVKO36ne2ryPANEXQfke4ksAjXhEKCrXjwVJOH5c1LeU6pxL7cjf2rmbVAJdmAcqvth1K0thAW2N7BfQXLJVXtQnezxly/mbA5HAoJKw=
before_script:
  - cd client && openssl aes-256-cbc -K $encrypted_dbdfbec4d753_key -iv $encrypted_dbdfbec4d753_iv -in env.js.enc -out env.js -d
  - cd ../server && openssl aes-256-cbc -K $encrypted_539b270f44b8_key -iv $encrypted_539b270f44b8_iv -in .env.enc -out .env -d
  - cd ../server && openssl aes-256-cbc -K $encrypted_539b270f44b8_key -iv $encrypted_539b270f44b8_iv -in toolsio-com-dd8a403a5115.json.enc -out -d
  - cd ../client && npm install && npm run forever:start src/index.js
  - cd ../server && npm install && npm run build
  - sleep 3
  - cd ../server && docker-compose build
  - cd ../server && docker-compose up -d
  - sleep 3
script:
  - cd ../client && npm run cypress:run
after_script:
  - cd ../client && npm run forever:stop src/index.js
  - cd ../server && npm run kill:test:server
  - cd ../server && docker-compose kill
