language: node_js
node_js:
  - "9.2.0"
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - birhanu.hailemariam@gmail.com
cache:
  directories:
    - client/node_modules
    - server/node_modules
env:
  - TEST_DIR=client
  - TEST_DIR=server
script:
  - cd $TEST_DIR && npm install && npm run tstart && npm test -- --runInBand
  #- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: develop





