language: node_js
node_js:
  - "10.2.1"
services:
  - if [ "$TEST_DIR" = "server" ]; then redis-server; fi
  - if [ "$TEST_DIR" = "server" ]; then docker; fi
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - birhanu.hailemariam@gmail.com
cache:
  directories:
    - client/node_modules
    - server/node_modules
env:
  - TEST_DIR=client
  - TEST_DIR=server
#before_script:
#  - cd $TEST_DIR && npm install
#script:
#  - cd $TEST_DIR && npm install && npm test
  #- npm run build
cache:
   directories:
     - node_modules
before_script:
  - cd $TEST_DIR 
  - npm install
  - if [ "$TEST_DIR" = "server" ]; then npm run build; fi
  - if [ "$TEST_DIR" = "server" ]; then sleep 3; fi
  - if [ "$TEST_DIR" = "server" ]; then docker-compose build; fi
  - if [ "$TEST_DIR" = "server" ]; then docker-compose up -d; fi
  - if [ "$TEST_DIR" = "server" ]; then sleep 3; fi
script:
#  - npm test
  - if [ "$TEST_DIR" = "client" ]; then npm run cypress:open; fi
  - if [ "$TEST_DIR" = "server" ]; then npm test; fi
after_script:
  - if [ "$TEST_DIR" = "server" ]; then docker-compose kill; fi

#jobs:
#  include:
#    - stage: test
#      script: 
#        - cd server && npm test -- --runInBand
#    - stage: deploy
#      deploy:
#        provider: pages
#        skip_cleanup: true
#        github_token: $github_token
#        local_dir: build
#        on:
#          branch: develop
      






