# [START runtime]
runtime: nodejs8
api_version: 1
instance_class: F2

env_variables:
  BUCKET_NAME: "toolsio.com"

handlers:
- url: /(.*\.html)
  mime_type: text/html 
  static_files: dist/\1 
  upload: dist/(.*\.html)

- url: /(.*\.css) 
  mime_type: text/css 
  static_files: dist/\1 
  upload: dist/(.*\.css)

- url: /(.*\.js) 
  mime_type: text/javascript 
  static_files: dist/\1 
  upload: dist/(.*\.js)

- url: /(.*\.map) 
  mime_type: text/javascript 
  static_files: dist/\1 
  upload: dist/(.*\.map)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|svg|woff|woff2|eot|ttf)) 
  static_files: dist/\1 
  upload: dist/(.*\.(bmp|gif|ico|jpeg|jpg|png|svg|woff|woff2|eot|ttf))

#- url: /
#  static_dir: dist

- url: /(.*)
  static_files: dist/index.html 
  upload: dist/index.html

- url: / 
  static_files: dist/index.html 
  upload: dist/index.html

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

#error_handlers:
  #- file: dist/error_pages//default_error.html

  # - error_code: dist/error_pages/over_quota
  #   file: dist/error_pages/over_quota.html

  # - error_code: dist/error_pages/dos_api_denial
  #   file: dist/error_pages/dos_api_denial.html

  # - error_code: dist/error_pages/timeout
  #   file: dist/error_pages/timeout.html

#- url: /
#  static_files: dist/index.html
#  upload: dist/index.html
#  secure: always

# - url: /(.*)
#   static_files: dist/index.html
#   upload: dist/index.html
#   secure: always

#- url: /
#  static_dir: dist

# - url: /
#   static_files: dist/index.html
#   upload: dist/index.html
#   secure: always

# - url: /
#   static_dir: dist


#- url: /api/.*
#  script: _go_app
# [END runtime]
