# [START runtime]
runtime: nodejs8
api_version: 1
instance_class: F2

env_variables:
  BUCKET_NAME: "toolsio.com"

handlers:

- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

# - url: /(.*)
#   static_files: dist/index.html
#   upload: dist/index.html
#   secure: always

- url: /
  static_dir: dist

#env: flex
#runtime: nodejs

# - url: /
#   static_files: dist/index.html
#   upload: dist/index.html
#   secure: always

# - url: /
#   static_dir: dist

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

#- url: /api/.*
#  script: _go_app
# [END runtime]
