version: '3'
services:
  redis: 
    image: redis
    networks: 
      - webnet
  db: 
    image: postgres
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "3030:5432"
    networks: 
      - webnet
    environment: 
      POSTGRES_USER: toolsio
      POSTGRES_PASSWORD: toolsio
      POSTGRES_DB: toolsio
  web:
    image: toolsio-server
    #image: birham/toolsio-server:latest # To use the image that's in docker cloud
    #ports:
    #  - "8080:8080" # We don' need to open up our port to the word, ngix handles it
    networks:
      - webnet 
    environment: 
      NODE_ENV: production
      SERVER_PORT: 8080
      REDIS_HOST: redis
      #SERVER_URL: https://toolsio.com
      #DB_HOST: db # We would need this if we use env variables in Sequelize constructor instead of json
    volumes:
    #  - .:/app  
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    #command: "node dist/index.js"
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "dist/index.js"]
  migration:
    build: .
    image: toolsio-server
    networks:
      - webnet 
    environment: 
      NODE_ENV: production
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
      - web
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "db:migrate"]
  nginx: 
    image: nginx
    networks:
      - webnet 
    volumes:
      - ./toolsio.template:/etc/nginx/conf.d/toolsio.template
      - ./uploads:/uploads
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=toolsio.com
      - NGINX_PORT=80
      - HTTP_UPGRADE=""
    depends_on: 
      - web
    command: /bin/bash -c "cat < /etc/nginx/conf.d/toolsio.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"  
    #command: [nginx-debug, '-g', 'daemon off;'] # Run nginx in debug mode
networks:
  webnet: 

    