version: '3'
services:
  redis: 
    image: redis
    networks: 
      - webnet
  db: 
    image: postgres
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "3030:5432"
    networks: 
      - webnet
    environment: 
      POSTGRES_USER: toolsio
      POSTGRES_PASSWORD: toolsio
      POSTGRES_DB: toolsio
  web:
    image: toolsio-server
    ports:
      - "8080:8080"
    networks:
      - webnet 
    environment: 
      NODE_ENV: production
      SERVER_PORT: 8080
      REDIS_HOST: redis
      #DB_HOST: db # We would need this if we use env variables in Sequelize constructor instead of json. 
    #volumes:
    #  - .:/app  
    depends_on:
      - db
      - redis
    #command: "node dist/index.js"
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "dist/index.js"]
    #command: sequelize db:migrate
networks:
  webnet: 