// MESSAGE
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

// USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// SALES
export const SET_SALES = 'SET_SALES'
export const ADD_SALE = 'ADD_SALE'
export const SALE_FETCHED = 'SALE_FETCHED'
export const SALE_UPDATED = 'SALE_UPDATED'
export const SALE_DELETED = 'SALE_DELETED'

// PROJECTS
export const SET_PROJECTS = 'SET_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const PROJECT_FETCHED = 'PROJECT_FETCHED'
export const PROJECT_UPDATED = 'PROJECT_UPDATED'
export const PROJECT_DELETED = 'PROJECT_DELETED'

// CUSTOMERS
export const SET_CUSTOMERS = 'SET_CUSTOMERS'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const CUSTOMER_FETCHED = 'CUSTOMER_FETCHED'
export const CUSTOMER_UPDATED = 'CUSTOMER_UPDATED'
export const CUSTOMER_DELETED = 'CUSTOMER_DELETED'

// TASKS
export const SET_TASKS = 'SET_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const TASK_FETCHED = 'TASK_FETCHED'
export const TASK_UPDATED = 'TASK_UPDATED'
export const TASK_DELETED = 'TASK_DELETED'

// ITEMS
export const SET_ITEMS = 'SET_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'
export const ITEM_FETCHED = 'ITEM_FETCHED'
export const ITEM_UPDATED = 'ITEM_UPDATED'
export const ITEM_DELETED = 'ITEM_DELETED'