// MESSAGE
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

// USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// PROJECTS
export const SET_SALES = 'SET_SALES'
export const ADD_SALE = 'ADD_SALE'
export const SALE_FETCHED = 'SALE_FETCHED'
export const SALE_UPDATED = 'SALE_UPDATED'
export const SALE_DELETED = 'SALE_DELETED'

// SALES
export const SET_PROJECTS = 'SET_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const PROJECT_FETCHED = 'PROJECT_FETCHED'
export const PROJECT_UPDATED = 'PROJECT_UPDATED'
export const PROJECT_DELETED = 'PROJECT_DELETED'