// MESSAGE
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

// ACCOUNT
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT'
export const ACCOUNT_FETCHED = 'ACCOUNT_FETCHED'
export const ACCOUNT_UPDATED = 'ACCOUNT_UPDATED' 

// RECIPIENTS
export const SET_USERS = 'SET_USERS'
export const USER_UPDATED = 'USER_UPDATED'

// SALES
export const SET_SALES = 'SET_SALES'
export const ADD_SALE = 'ADD_SALE'
export const SALE_FETCHED = 'SALE_FETCHED'
export const SALE_UPDATED = 'SALE_UPDATED'
export const SALE_DELETED = 'SALE_DELETED'

// PROJECTS
export const SET_PROJECTS = 'SET_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const PROJECT_FETCHED = 'PROJECT_FETCHED'
export const PROJECT_UPDATED = 'PROJECT_UPDATED'
export const PROJECT_DELETED = 'PROJECT_DELETED'

// CUSTOMERS
export const SET_CUSTOMERS = 'SET_CUSTOMERS'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const CUSTOMER_FETCHED = 'CUSTOMER_FETCHED'
export const CUSTOMER_UPDATED = 'CUSTOMER_UPDATED'
export const CUSTOMER_DELETED = 'CUSTOMER_DELETED'

// TASKS
export const SET_TASKS = 'SET_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const TASK_FETCHED = 'TASK_FETCHED'
export const TASK_UPDATED = 'TASK_UPDATED'
export const TASK_DELETED = 'TASK_DELETED'

// ITEMS
export const SET_ITEMS = 'SET_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'
export const ITEM_FETCHED = 'ITEM_FETCHED'
export const ITEM_UPDATED = 'ITEM_UPDATED'
export const ITEM_DELETED = 'ITEM_DELETED'

// INVOICES
export const SET_INVOICES = 'SET_INVOICES'
export const ADD_INVOICE = 'ADD_INVOICE'
export const INVOICE_FETCHED = 'INVOICE_FETCHED'
export const INVOICE_UPDATED = 'INVOICE_UPDATED'
export const INVOICE_DELETED = 'INVOICE_DELETED'

// CONVERSATIONS
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS'
export const ADD_CONVERSATION = 'ADD_CONVERSATION'
export const CONVERSATION_FETCHED = 'CONVERSATION_FETCHED'
export const INBOX_OR_SENT_FETCHED = 'INBOX_OR_SENT_FETCHED'
export const CONVERSATION_DELETED = 'CONVERSATION_DELETED'   

// MESSAGES
export const MESSAGES = 'MESSAGES'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_FETCHED = 'MESSAGE_FETCHED'

// DASHBOARD
export const SET_DASHBOARDS_TOTAL_INCOME = 'SET_DASHBOARDS_TOTAL_INCOME'
export const SET_DASHBOARDS_INCOMES = 'SET_DASHBOARDS_INCOMES'
export const SET_DASHBOARDS_PROJECTS = 'SET_DASHBOARDS_PROJECTS'
export const SET_DASHBOARDS_SALES = 'SET_DASHBOARDS_SALES'
export const SET_DASHBOARDS_INVOICES = 'SET_DASHBOARDS_INVOICES'
export const SET_DASHBOARDS_CUSTOMERS = 'SET_DASHBOARDS_CUSTOMERS'
export const SET_DASHBOARDS_PROJECT_TASKS = 'SET_DASHBOARDS_PROJECT_TASKS'
export const SET_DASHBOARDS_SALE_TASKS = 'SET_DASHBOARDS_SALE_TASKS'
export const SET_DASHBOARDS_INVOICE_TASKS = 'SET_DASHBOARDS_INVOICE_TASKS'

